### ISSUE TITLE
Flesh out descriptions of included datasets

### ISSUE THREAD

**Issue by steffilazerte** [steffilazerte/envirocan#13]

**Comment by boshek** [comment]
I did this in `sam_work` for `kamloops` and `pg`. All I did was add the columns. Is that what you were thinking?

**Comment by steffilazerte** [comment]
Yup, just following the example from <http://r-pkgs.had.co.nz/data.html> under Documenting Datasets

**Comment by boshek** [comment]
Fixed and committed to `sam_work`.
