### ISSUE TITLE
Need a vignette

### ISSUE THREAD

**Issue by boshek** [steffilazerte/envirocan#15]
In advance of a CRAN submission I think it is prudent to have a good vignette built. The README is basically there but I think we could highlight a few more of the intricacies. Particularly I think we could flesh out the time interval argument explanation. That wasn't immediately obvious to me.

**Comment by steffilazerte** [comment]
By the way, I've started working on updating the README vignette. I'm looking into using [pkgdown](http://hadley.github.io/pkgdown/) to turn the README/vignettes into a simple website to host on github.

**Comment by boshek** [comment]
Oh yeah - the pkgdown is so good. I think there might be a distinction between the README and vignette too. Have a look at the dplyr CRAN page: https://cran.r-project.org/web/packages/dplyr/index.html
They have general usage covered by the README then more specific applications covered by vignettes. I wonder if the multiple station searches (using purrr)  and then interpolate and add data stuff might be best as sub vignettes?

**Comment by steffilazerte** [comment]
That makes sense, the README can cover immediate usage (find station, get data), the vignettes more advanced/specific applications
