### ISSUE TITLE
Quiet mode and progress bar for weather

### ISSUE THREAD

**Issue by boshek** [steffilazerte/envirocan#18]
- Need an argument so that `weather()` doesn't always have output. 
- A progress bar might be useful though I'm not totally clear how that interact with web scraping

**Comment by steffilazerte** [comment]
I always like 'verbose = FALSE/TRUE' for output messages. 

A progress bar could work if there are multiple downloads (like downloading a year's worth of hourly data), but it won't apply to single downloads... Which I guess is fine, because single downloads go pretty fast.

I'll look into it

**Comment by boshek** [comment]
You are right on the progress I think. Might not be useful right now.

The thing that I don't love about verbose is that it isn't totally clear what it means. I prefer `quiet=FALSE/TRUE`. But not a huge deal.
